version: '3.8'

services:
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  api-prod:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge