spring:
  jackson:
    time-zone: Asia/Bangkok
  datasource:
    url: jdbc:mysql://mydb.cr8guweee4v5.ap-southeast-2.rds.amazonaws.com:3306/grooming
    username: admin
    password: admin1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
jwt:
  secret-key: NkQyYzNsbmQxNTJhZTJwZ2p2ZGZ5bjRkdmkwb0x6W0xFSF5Gb+OXy7hOjz7hGjmI==
  expiration: 86400000 # 1 วัน (มิลลิวินาที)