spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/prod?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok}
    username: ${SPRING_DATASOURCE_USERNAME:prod}
    password: ${SPRING_DATASOURCE_PASSWORD:prodpass}
  jpa:
    show-sql: false

jwt:
  secret-key: ${JWT_SECRET:1234567890}
  expiration: 86400000

payment:
  promptpay:
    receiverPhone: "0818092589"
    expiresSeconds: 300
