spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none    # สะดวกตอน dev
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret-key: ${JWT_SECRET:CHANGE_ME_FOR_DEV_ONLY}
  expiration: 86400000   # 1 วัน (ms)

payment:
  promptpay:
    receiverPhone: "0818092589"
    expiresSeconds: 300

