spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
    username: admin
    password: 1234

jwt:
  secret-key: 1234567890
  expiration: 86400000

payment:
  promptpay:
    receiverPhone: "0818092589"
    expiresSeconds: 300
