spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: admin
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
jwt:
  secret-key: bossodiz
  expiration: 86400000 # 1 วัน (มิลลิวินาที)