spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate    # สะดวกตอน dev
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: DEBUG

# !!! แนะนำมาก: อย่า hardcode ความลับในไฟล์
# ให้เปลี่ยนเป็นอ่านจาก ENV (ด้านล่างมีตัวอย่าง)
jwt:
  secret-key: ${JWT_SECRET:CHANGE_ME_FOR_DEV_ONLY}
  expiration: 86400000   # 1 วัน (ms)

payment:
  promptpay:
    receiverPhone: "0818092589"
    expiresSeconds: 300
