spring:
  jackson:
    time-zone: Asia/Bangkok
  datasource:
    url: jdbc:mysql://root:PvDhNGQhBHMdbSDGOuUfUiTQjMFLQPOX@shuttle.proxy.rlwy.net:22978/railway
    username: root
    password: PvDhNGQhBHMdbSDGOuUfUiTQjMFLQPOX
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
jwt:
  secret-key: NkQyYzNsbmQxNTJhZTJwZ2p2ZGZ5bjRkdmkwb0x6W0xFSF5Gb+OXy7hOjz7hGjmI==
  expiration: 86400000 # 1 วัน (มิลลิวินาที)