server:
  servlet:
    context-path: /api
spring:
  jackson:
    time-zone: Asia/Bangkok
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: admin
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
jwt:
  secret-key: NkQyYzNsbmQxNTJhZTJwZ2p2ZGZ5bjRkdmkwb0x6W0xFSF5Gb+OXy7hOjz7hGjmI==
  expiration: 86400000 # 1 วัน (มิลลิวินาที)

payment:
  promptpay:
    receiverPhone: "0818092589"   # หรือคอมเมนต์บรรทัดนี้ถ้าใช้ National ID
    expiresSeconds: 300           # เวลาให้ลูกค้าสแกน (วินาที)
