name: Build & Deploy API
on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/grooming-api:latest
            ${{ secrets.DOCKERHUB_USER }}/grooming-api:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/grooming-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/grooming-api:buildcache,mode=max

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/apps/grooming
            docker compose pull api
            docker compose up -d api
